### ISSUE TITLE
cannot delete file

### ISSUE THREAD

**Issue by divinites** [math2001/FileManager#4]
Thanks for your updating, now creating file works. However, I cannot delete file.

```python
Traceback (most recent call last):
  File "FileManager in /Users/divinites/Library/Application Support/Sublime Text 3/Installed Packages/FileManager.sublime-package", line 476, in delete
  File "FileManager in /Users/divinites/Library/Application Support/Sublime Text 3/Installed Packages/FileManager.sublime-package", line 169, in close_file_poyfill
TypeError: 'NoneType' object is not callable
```

**Comment by math2001** [comment]
What version of sublime text are you using?

**Comment by divinites** [comment]
Yes, your update works, thanks.
