### ISSUE TITLE
stopped working for me

### ISSUE THREAD

**Issue by fake-fur** [math2001/FileManager#57]
hi

love the package and have used it for ages but suddenly it has stopped working - the context menu no longer appears

i uninstalled and reinstalled with no errors - did not touch the package settings - nothing works

i am running debian + gnome ST3 latest

thanks

**Comment by math2001** [comment]
Damn that's really weird. Can you make sure `FileManager` isn't disabled? I don't see how else it could be that no option would show up in the context menu.

Can you try to [revert to a fresh state](https://gist.github.com/math2001/04186bb2273fa5accc04f88e44275d49) and install FileManager to see if it works? I've just done that and I haven't had any issues.

Another possibility is that it's conflicting with an other plugin (but that would be weird because that would mean that other plugin would be *explicitely* disabling FileManager's context menu entries).

Maybe you extracted (using something like `PackageResourceViewer` maybe?) the `Side Bar.sublime-menu` file, and your version is empty or something like that. Go to `Preferences -> Browse Packages` and make sure that you don't have a folder called `FileManager`. If you do, look inside and tell me what you have. A quick fix would be to remove it (or just move it outside of the `Packages` folder).

> did not touch the package settings

Does that mean you haven't go any user setting, or that you didn't change your settings since last time it worked? In the later case, you you please copy/paste your settings in here just so that I can have a look?

**Comment by ebithril** [comment]
I have a similar issue except that I never use the context menu so I don't know if that still works for me, however I can't find any of the FileManager commands through ctrl+alt+p so I would guess that it's the same issue. I'm on windows 10 running ST3 verions 3.2.2 build 3211

**Comment by fake-fur** [comment]
hi again - sorry for the delay getting back to you

i rebooted my machine and things started working again - no clue what that means but i am surprised a reboot could affect a text editor plugin

i won't mark as closed as other people seem to have the same issue ut if you want to close this you can

thanks and sorry for the sorta false alarm

**Comment by math2001** [comment]
> i am surprised a reboot could affect a text editor plugin

Same here... Maybe it's not a problem with FileManager itself, though if that happens only with this package, I don't know what else it could be with.

> sorry for the sorta false alarm

No no, thank you for reporting, it's a problem. Especially since other people seem to have similar experience.

@ebithril could you paste your console content here (when FileManager isn't working). Like, go to `View -> Show Console` and copy everything. I just want to see if FileManager is loaded at all.

After that, could you try and reboot like @fake-fur to see if that solves your problem?

**Comment by ebithril** [comment]
[filemanager.log](https://github.com/math2001/FileManager/files/4059930/filemanager.log)
here is the parts of the log that seems to have anything to do filemanager. Thanks for looking into this.

**Comment by ebithril** [comment]
[filemanager.log](https://github.com/math2001/FileManager/files/4060016/filemanager.log)
here is everything that has to do with filemanager in the log. Thanks for looking into this

**Comment by math2001** [comment]
Just a quick note: if you only pasted the logs from FileManager because you don't want to share the rest, then that's completely fine, I respect that :slightly_smiling_face: . But otherwise, it would be really helpful if you could give me the *entire* log (`ctrl+a`, `ctrl+c`) when you see the bug.

### Just my own thoughts

Thanks for the log! Damn that's kind of weird. ~~What's happening is that it's calling the `is_visible` method while the sublime text api is loading, hence `import sublime` is just `None` (so `sublime.load_settings()` fails).~~ `is_visible` is called whilst `sublime` is `None`, which I don't how it's even possible. When the API is loading, `import sublime` still gives an object that just doesn't do anything, but not `None`.

Just FYI: `is_visible` can is triggered when you open up the command palette or a menu.

Oh, I have an idea. See this line in your log `Package Control: Upgraded FileManager to 1.4.14`?

I've been rolling out a fair few updates lately, and maybe it's this upgrading that's causing trouble. Maybe that's what's causing `sublime` to be `None`. Could you tell me whether you still get this bug once package control no longer updates this plugin for you? (`1.4.14` is currently the last version (15 jan 08:26 AEST))

I'm not sure how package control behaves when it sees multiple versions to update (does it jump straight to the latest or install each one by one). Maybe the reason you get this working/not working is if it does each install one by one (and they are all each spaced out one hour, the time it waits to check for updates).

Another indicator that it might be an issue with package control is that, in my console (st 3211 win 10) the line after `reloading plugin FIleManager.sublimefunctions` is `Package Control.1_reloader`. I'm guessing it's between these two lines that all the errors occurs in your log.

### What you can do to help me out

#### First possibility: conflict with other packages

Maybe it conflicts with other packages. It would be really helpful if you could try to [revert to a fresh state](https://gist.github.com/math2001/04186bb2273fa5accc04f88e44275d49) (you can easily get back to how you were before), install package control (`Tools -> Install Package Control`), install FileManager, restart sublime, and see if you still get this bug. If you do, then that means it's definitely just a problem with FileManager, and not some conflict between plugins.

If you do see the bug, then record the logs, with a short description (like `Fresh state logs, got bug`) just to make sure we don't mix things up.

If you don't get the bug anymore, then record the logs too, it'll be intersting to see if we do get all those errors (short description like `Fresh state logs, no bug`).

#### Second possibility: problem with package control updates

Next time you get a bug check that you currently have the last version:

1. `Package Control: List Packages`, the version is written in small under FileManager. That'll give you the version currently installed on your system.
2. check up against the latest version on [the website](https://packagecontrol.io/packages/FileManager). 

If it is the same version on both, look in the console and try to find a line `PackageControl: Upgraded ...`. If you do see that, then restart sublime (and make sure again that you have the latest version and that package control hasn't updated). If you still get the bug after that, then my best bet is conflict with other plugins (which I hope you will have checked by reverting to a fresh state). Remember to give me the logs (description `Regular state, got bug`).

If it's neither of those two options, then we'll have to think some more :slightly_smiling_face: Just know that the more verbose you are, the better (give me a *shit tone* of logs please :smile: ). This is a very weird bug that I can't yet replicate, so there isn't much I can do to fix it right now.

**Comment by fake-fur** [comment]
hi again

so it suddenly came back again and is now doing the exact same thing - basically not there anymore

i am on the latest version - other packages i have installed are:
1. git gutter
2. blade highlighter
3. predawn theme
4. visual studio dark editor theme

that's all

thanks for your time on this btw

**Comment by math2001** [comment]
Alright, it's probably not a problem with other plugins.

I wonder if #59 could have fixed this/affected this (the changes in there haven't been released yet).

Actually, @deathaxe, just eyeballing it, do you think that could have to do with the loading of the modules? The fact that `sublime` is `None` seems really weird to me, but it seems not too far fetched to think that it could happen if the packages are reloaded weirdly.

I actually just hit that bug today. I think it was when I was switching branches on FileManager. So I copied the logs. Though I should have opened the console and `print(sublime)` and try to `import sublime` again, just to see.

<details>

<summary>Logs</summary>

```
Packages installed:

- ChannelRepositoryTools
- LSP
- Package Control
- PackageDev
- PackageResourceViewer
- ProjectManager
- TypeScript
- UnitTesting

startup, version: 3211 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/math2001/.config/sublime-text-3/Packages
state path: /home/math2001/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/math2001/.config/sublime-text-3/Installed Packages
ignored_packages: ["ChannelRepositoryTools", "MarkdownLivePreview", "Vintage"]
pre session restore time: 0.274121
startup time: 0.347162
git: tracking working dir /home/math2001/.config/sublime-text-3/Packages/FileManager
first paint time: 0.380635
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-package_setting_context
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.01-sublime_lib
reloading plugin 0_package_control_loader.15-coverage
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pathlib
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-bs4
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin LSP.boot
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageDev._logging
reloading plugin PackageDev.main
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin ProjectManager.json_file
reloading plugin ProjectManager.project_manager
reloading plugin AutoCloseEmptyGroup.AutoCloseEmptyGroup
reloading plugin Blackd.blackd
reloading plugin FileManager.FileManager
reloading plugin FileManager.prevent_default
reloading plugin JSONComma.jsoncomma
reloading plugin JSONComma.server
reloading plugin package_setting_context.__init__
reloading plugin reload_plugin.reload_plugin
reloading plugin TypeScript.main
2020-01-18 11:41:44,277: 140206033818752: WARNING: TypeScript plugin initialized.
reloading plugin UnitTesting.ut
reloading plugin User.expand_selection_to
reloading plugin User.hooks
reloading plugin User.offset
plugins loaded
lang_service_enabled: True
Path of tsserver.js: /home/math2001/.config/sublime-text-3/Packages/TypeScript/tsserver/tsserver.js
Path of tsc.js: /home/math2001/.config/sublime-text-3/Packages/TypeScript/tsserver/tsc.js
Trying to spawn node executable from: /usr/bin/node
ref view not found
JSONComma: checking last release...
JSONComma: {'details': {'Net': 'tcp', 'Addr': {'Zone': '', 'Port': 2442, 'IP': '127.0.0.1'}, 'Op': 'listen', 'Err': {'Syscall': 'bind', 'Err': 98}, 'Source': None}, 'context': 'opening socket', 'kind': 'error', 'error': 'listen tcp 127.0.0.1:2442: bind: address already in use'}
JSONComma: assume already running
Package Control: Skipping automatic upgrade, last run at 2020-01-18 11:33:24, next run at 2020-01-18 12:33:24 or after
loading dictionary Packages/Language - English/en_US.dic
reloading plugin FileManager.FileManager
reloading plugin FileManager.input_for_path
reloading plugin FileManager.pathhelper
reloading plugin FileManager.sublimefunctions
reloading plugin FileManager.FileManager
unloading plugin FileManager.input_for_path
unloading plugin FileManager.pathhelper
unloading plugin FileManager.sublimefunctions
reloading plugin FileManager.FileManager
reloading plugin FileManager.input_for_path
reloading plugin FileManager.pathhelper
reloading plugin FileManager.sublimefunctions
git: untracking working dir /home/math2001/.config/sublime-text-3/Packages/FileManager
git: tracking working dir /home/math2001/.config/sublime-text-3/Packages/FileManager
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/FMcommands/appcommand.py", line 8, in is_visible
    settings = get_settings()
  File "/home/math2001/.config/sublime-text-3/Packages/FileManager/sublimefunctions.py", line 32, in get_settings
    return sublime.load_settings("FileManager.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

</details>

> ok so quitting and restarting ST made it work again - maybe the update weirdness happens and it is confused until it is restarted - or something

Same thing here. I'll try to play around with checking out branches again, to see if that causes anything.

Thanks for your report @fake-fur :hearts:
