### ISSUE TITLE
Duplicate chokes on non-ascii files

### ISSUE THREAD

**Issue by bordaigorl** [math2001/FileManager#68]
Love the plugin, but it's failing to duplicate files that contain unicode characters.
For some characters (e.g. ✓) it still duplicates the file but with missing chars.
For some other unicode characters (e.g. ⊎) it crashes with exception:

```
Traceback (most recent call last):
  File "/Users/bordaigorl/Library/Application Support/Sublime Text 3/Installed Packages/FileManager.sublime-package/libs/input_for_path.py", line 304, in input_on_done
  File "/Users/bordaigorl/Library/Application Support/Sublime Text 3/Installed Packages/FileManager.sublime-package/commands/duplicate.py", line 58, in duplicate
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8: ordinal not in range(128)
```

Sounds like a `decode` was called with default encoding of `ascii`.
I wonder if it would be better to just use a syscall to copy the file...

**Comment by TheSecEng** [comment]
@bordaigorl thanks for thee report, I'll look into this today.
